### ISSUE TITLE
What data should be put in ktboth when I run python train.py?

### ISSUE THREAD

**Issue by disco14** [ayanc/fdscs#4]
Sorry to bother you, I want to know what data should be put in ktboth directory? When I run python train.py, an error occurred in the program. I thought about it. 000004_15.png is not a data format in kitti. So what kind of data is this?  Should I change the data from the end of 10,11 to the end of 12,15?

Regards. 
Thank you.

Details:
2020-01-05 20:17:30.099653: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at whole_file_read_ops.cc:114 : Not found: data/ktboth/left/000004_15.png; No such file or directory
2020-01-05 20:17:30.099684: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at whole_file_read_ops.cc:114 : Not found: data/ktboth/right/000077_15.png; No such file or directory
2020-01-05 20:17:30.099655: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at whole_file_read_ops.cc:114 : Not found: data/ktboth/left/000175_15.png; No such file or directory
2020-01-05 20:17:30.099657: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at whole_file_read_ops.cc:114 : Not found: data/ktboth/right/000175_15.png; No such file or directory
2020-01-05 20:17:30.099736: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at whole_file_read_ops.cc:114 : Not found: data/ktboth/disp/000077_15.png; No such file or directory
2020-01-05 20:17:30.099743: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at whole_file_read_ops.cc:114 : Not found: data/ktboth/right/000183_15.png; No such file or directory
2020-01-05 20:17:30.099686: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at whole_file_read_ops.cc:114 : Not found: data/ktboth/left/000077_15.png; No such file or directory
2020-01-05 20:17:30.099655: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at whole_file_read_ops.cc:114 : Not found: data/ktboth/disp/000004_15.png; No such file or directory
2020-01-05 20:17:30.099730: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at whole_file_read_ops.cc:114 : Not found: data/ktboth/left/000183_15.png; No such file or directory
2020-01-05 20:17:30.099660: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at whole_file_read_ops.cc:114 : Not found: data/ktboth/right/000004_15.png; No such file or directory
2020-01-05 20:17:30.099681: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at whole_file_read_ops.cc:114 : Not found: data/ktboth/disp/000175_15.png; No such file or directory
2020-01-05 20:17:30.099750: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at whole_file_read_ops.cc:114 : Not found: data/ktboth/disp/000183_15.png; No such file or directory
Traceback (most recent call last):
  File "/home/UE4/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/home/UE4/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/UE4/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.NotFoundError: data/ktboth/left/000004_15.png; No such file or directory
	 [[{{node ReadFile_9}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 82, in <module>
    outs = sess.run(vals,feed_dict=d.fdict(blst))
  File "/home/UE4/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/UE4/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/UE4/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/home/UE4/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: data/ktboth/left/000004_15.png; No such file or directory
	 [[node ReadFile_9 (defined at /home/UE4/research/Network/fdscs-master/data.py:45) ]]

Caused by op 'ReadFile_9', defined at:
  File "train.py", line 36, in <module>
    d = data.dataset(BSZ)
  File "/home/UE4/research/Network/fdscs-master/data.py", line 105, in __init__
    self.graph()
  File "/home/UE4/research/Network/fdscs-master/data.py", line 45, in graph
    limg = tf.image.decode_jpeg(tf.read_file(self.left[i]),channels=3)
  File "/home/UE4/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/ops/gen_io_ops.py", line 589, in read_file
    "ReadFile", filename=filename, name=name)
  File "/home/UE4/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/home/UE4/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/UE4/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/home/UE4/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

NotFoundError (see above for traceback): data/ktboth/left/000004_15.png; No such file or directory
	 [[node ReadFile_9 (defined at /home/UE4/research/Network/fdscs-master/data.py:45) ]]

**Comment by ayanc** [comment]
Take a look at the training code: your training data should be located according to the naming convention in data.py and data/train.txt. If necessary, you should edit these files.

The current code is in a format where (for KITTI training), the left/right/gt images are in left, right, and disp sub-directiories of data/ktboth. The _12 and _15 refers to images (the _10 images, for which there is GT disparity) from the KITTI 2012 and 2015 training sets.
